config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do 
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end

  end
  
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy] 
  resources :friendships, only: [:create, :destroy] do
    member do
      post :cancel
      post :accept
      get :check
    end
  end

  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index" 
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader

   # 「使用者評論很多餐廳」的多對多關聯
  has_many :comments
  has_many :restaurants, through: :comments, dependent: :restrict_with_error
  
  # 「使用者收藏很多餐廳」的多對多關聯
  # 讓 User 物件可以得到 object.favorites 等關聯方法
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  # 「使用者like很多餐廳」的多對多關聯
  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant
  
  # 讓 User 可以找到他追蹤的人
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # 讓 User 可以找到他的追蹤者
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  # User 可以找到他加入的好友
  has_many :friendships, dependent: :destroy
  has_many :friendings, through: :friendships

  # User 可以找到加入他的好友
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friending_id"
  has_many :frienders, through: :inverse_friendships, source: :user


  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def friending?(user)
    self.friendings.include?(user)
  end

  def friend?(user)
    self.friends.include?(user)
  end

  def inverse_friend?(user)
    self.inverse_friends.include?(user)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers= @user.followers
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @user = User.find(params[:id])
    # @friendings = @user.friendings
    # @frienders = @user.frienders
    @all_friends = (@user.friendings + @user.frienders).uniq
  end

  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    


        <div class="col-md-9 col-sm-8">
          <%= form_for [@user] do |f| %>
            <div class="form-group">
              <%= f.label :name, "Name" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :intro, "Intro" %>
              <%= f.text_area :intro, class: "form-control" %>
            </div>
            
            <%= f.label :avatar, "Photo" %>
            <%= image_tag @user.avatar, width: '300px' if @user.avatar? %>
            <%= f.file_field :avatar %>

            <br>
            
            <div class="form-group">
              <%= f.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>

        <div class="clearfix"></div>


      <br>


  </div>
</div>

app/views/users/friend_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <h1>friends</h1>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @all_friends.count %></strong> friends </h3>
        </div>

        <ul class="list-group">
          <% @all_friends.each do |all_friends| %>
          <li class="list-group-item">
            <%= link_to user_path(all_friends) do %>
            <img class="img-circle" src="http://via.placeholder.com/30x30">
            <%= all_friends.name %>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <!-- 使用 Bootstrap components 的 Nav Tabs -->
    <!-- https://getbootstrap.com/docs/3.3/components/#nav-tabs -->
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'Top 10 人氣餐聽', ranking_restaurants_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>

  </div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="page-header">
          <h1>美食達人</h1>
        </div>
      </div>

    <% @users.each do |user| %>
      <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
        <%= link_to user_path(user) do %>
          <!-- 可先利用 Placeholder 如 <img src="http://via.placeholder.com/128x128"> 產生圖片 -->
          <img class="img-rounded" src="http://via.placeholder.com/128x128">
          <h4><%= user.name %></h4>
        <% end %>
        
        <%= render partial: "shared/follow", locals: { user: user } %>
        <%= render partial: "shared/friend", locals: { user: user } %>

      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header">

        <div class="col-md-3 col-sm-4">
          <div class="text-center">
            <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <!-- inline & unstyled 的 list -->
          <ul class="list-unstyled list-inline">
            <li><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</li>
            <li><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</li>
            <li><strong><%= @followings.count %></strong> followings</li>
            <li><strong><%= @followers.count %></strong> followers</li>
          </ul>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
          <%= link_to 'Friends', friend_list_user_path(@user), class: "btn btn-primary" %>
        </div>
        <div class="clearfix"></div>

      </div>

      <br>

      <div class="col-md-4">
        <!-- 顯示followings的清單，panel包一個list-group  -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @followings.count %></strong> followings</h3>
          </div>

          <ul class="list-group">
            <% @followings.each do |following| %>
            <li class="list-group-item">
              <%= link_to user_path(following) do %>
              <img class="img-circle" src="http://via.placeholder.com/30x30">
              <!-- <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %> -->
              <%= following.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>

        <!-- 顯示followers的清單，panel包一個list-group  -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @followers.count %></strong> followers</h3>
          </div>

          <ul class="list-group">
            <% @followers.each do |follower| %>
            <li class="list-group-item">
              <%= link_to user_path(follower) do %>
              <img class="img-circle" src="http://via.placeholder.com/30x30">
              <%= follower.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-md-8">

        <!-- 顯示已評論餐廳的清單，panel包一個panel-body裡面使用row>col的layouts來顯示評論 -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
          </div>
          <div class="panel-body">
            <% @commented_restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
              <div>
                <img class="img-responsive img-rounded-circle" src="http://via.placeholder.com/100x80">
              </div>
              <h5><%= restaurant.name %></h5>
            </div>
            <% end %>

            <% end %>
          </div>
        </div>

        <!-- 顯示收藏的餐廳的清單，panel包一個panel-body裡面簡單顯示餐廳圖片和name -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</h3>
          </div>

          <div class="panel-body">
            <% @favorited_restaurants.each do |restaurant| %>
              <div class="my-restaurant">
                <div>
                  <%= link_to restaurant_path(restaurant) do %>
                    <img class="img-responsive img-rounded-circle" src="http://via.placeholder.com/80x60">
                    <!-- <%= image_tag restaurant.image, class: "img-responsive img-rounded" %> -->
                    <h5><%= restaurant.name %></h5>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

      </div>


    </div>
  </div>
</div>